spring:
  datasource:
    url: jdbc:mariadb://ryuseulgi.ckeivq86dt9b.ap-northeast-2.rds.amazonaws.com:3306/RYUSEULGI
    driver-class-name: org.mariadb.jdbc.Driver
    username: RYUSEULGI
    password: RYUSEULGI
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update